import * as PIXI from 'pixi.js';

PIXI.settings.SCALE_MODE = PIXI.SCALE_MODES.NEAREST;

const textures = {
  // Tiles
  hole: PIXI.Texture.from('assets/tiles/hole.png'),
  edge: PIXI.Texture.from('assets/tiles/edge.png'),
  ground: PIXI.Texture.from('assets/tiles/ground.png'),
  n: PIXI.Texture.from('assets/tiles/n.png'),
  s: PIXI.Texture.from('assets/tiles/s.png'),
  e: PIXI.Texture.from('assets/tiles/e.png'),
  w: PIXI.Texture.from('assets/tiles/w.png'),
  ne: PIXI.Texture.from('assets/tiles/ne.png'),
  nw: PIXI.Texture.from('assets/tiles/nw.png'),
  'w-e': PIXI.Texture.from('assets/tiles/w-e.png'),
  'n-nw-w': PIXI.Texture.from('assets/tiles/n-nw-w.png'),
  'n-ne-e': PIXI.Texture.from('assets/tiles/n-ne-e.png'),
  all: PIXI.Texture.from('assets/tiles/all.png'),
};

export const tilesSprites = {
  '-2': textures['hole'],
  '-1': textures['edge'],
  0: textures['ground'],
  1: textures['s'],
  2: textures['s'],
  3: textures['s'],
  4: textures['s'],
  5: textures['s'],
  7: textures['s'],
  6: textures['s'],
  8: textures['s'],
  9: textures['s'],
  10: textures['s'],
  11: textures['s'],
  12: textures['s'],
  13: textures['w-e'],
  14: textures['w-e'],
  15: textures['w-e'],
  16: textures['w-e'],
  17: textures['w-e'],
  18: textures['w-e'],
  19: textures['w-e'],
  20: textures['w-e'],
  21: textures['w-e'],
  22: textures['w-e'],
  23: textures['w-e'],
  24: textures['w-e'],
  25: textures['w-e'],
  26: textures['n-ne-e'],
  27: textures['n-ne-e'],
  28: textures['e'],
  29: textures['n-ne-e'],
  30: textures['n-ne-e'],
  31: textures['e'],
  32: textures['n-ne-e'],
  33: textures['e'],
  34: textures['n-nw-w'],
  35: textures['n-nw-w'],
  36: textures['w'],
  37: textures['n-nw-w'],
  38: textures['n-nw-w'],
  39: textures['n-nw-w'],
  40: textures['w'],
  41: textures['w'],
  42: textures['n'],
  43: textures['n'],
  44: textures['ne'],
  45: textures['nw'],
  46: textures['all'],
  47: textures['s'],
};
