import * as PIXI from 'pixi.js';
import {MonsterType, PropType} from 'libs/generate';

PIXI.settings.SCALE_MODE = PIXI.SCALE_MODES.NEAREST;

export const textures = {
  // Tiles
  hole: {name: 'hole', path: 'assets/tiles/', ext: '.png', texture: null},
  edge: {name: 'edge', path: 'assets/tiles/', ext: '.png', texture: null},
  ground: {name: 'ground', path: 'assets/tiles/', ext: '.png', texture: null},
  n: {name: 'n', path: 'assets/tiles/', ext: '.png', texture: null},
  s: {name: 's', path: 'assets/tiles/', ext: '.png', texture: null},
  e: {name: 'e', path: 'assets/tiles/', ext: '.png', texture: null},
  w: {name: 'w', path: 'assets/tiles/', ext: '.png', texture: null},
  ne: {name: 'ne', path: 'assets/tiles/', ext: '.png', texture: null},
  nw: {name: 'nw', path: 'assets/tiles/', ext: '.png', texture: null},
  w_e: {name: 'w_e', path: 'assets/tiles/', ext: '.png', texture: null},
  n_nw_w: {name: 'n_nw_w', path: 'assets/tiles/', ext: '.png', texture: null},
  n_ne_e: {name: 'n_ne_e', path: 'assets/tiles/', ext: '.png', texture: null},
  all: {name: 'all', path: 'assets/tiles/', ext: '.png', texture: null},
  // Props
  bone: {name: 'bone', path: 'assets/props/', ext: '.png', texture: null},
  crate_silver: {
    name: 'crate_silver',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  crate_wood: {
    name: 'crate_wood',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  flag: {name: 'flag', path: 'assets/props/', ext: '.png', texture: null},
  handcuff_1: {
    name: 'handcuff_1',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  handcuff_2: {
    name: 'handcuff_2',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  health_large: {
    name: 'health_large',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  health_small: {
    name: 'health_small',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  key_gold: {
    name: 'key_gold',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  key_silver: {
    name: 'key_silver',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  ladder: {name: 'ladder', path: 'assets/props/', ext: '.png', texture: null},
  lamp: {name: 'lamp', path: 'assets/props/', ext: '.png', texture: null},
  mana_large: {
    name: 'mana_large',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  mana_small: {
    name: 'mana_small',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  peak: {name: 'peak', path: 'assets/props/', ext: '.png', texture: null},
  skull: {name: 'skull', path: 'assets/props/', ext: '.png', texture: null},
  stones_large: {
    name: 'stones_large',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  stones_small: {
    name: 'stones_small',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  torch: {name: 'torch', path: 'assets/props/', ext: '.png', texture: null},
  web_left: {
    name: 'web_left',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  web_right: {
    name: 'web_right',
    path: 'assets/props/',
    ext: '.png',
    texture: null,
  },
  // Monsters
  bandit: {
    name: 'bandit',
    path: 'assets/monsters/',
    ext: '.png',
    texture: null,
  },
  centaur_female: {
    name: 'centaur_female',
    path: 'assets/monsters/',
    ext: '.png',
    texture: null,
  },
  centaur_male: {
    name: 'centaur_male',
    path: 'assets/monsters/',
    ext: '.png',
    texture: null,
  },
  mushroom_large: {
    name: 'mushroom_large',
    path: 'assets/monsters/',
    ext: '.png',
    texture: null,
  },
  mushroom_small: {
    name: 'mushroom_small',
    path: 'assets/monsters/',
    ext: '.png',
    texture: null,
  },
  skeleton: {
    name: 'skeleton',
    path: 'assets/monsters/',
    ext: '.png',
    texture: null,
  },
  troll: {name: 'troll', path: 'assets/monsters/', ext: '.png', texture: null},
  wolf: {name: 'wolf', path: 'assets/monsters/', ext: '.png', texture: null},
};

Object.keys(textures).forEach(key => {
  textures[key].texture = PIXI.Texture.from(
    `${textures[key].path}${key}${textures[key].ext}`,
  );
});

export const tilesSprites = {
  '-2': textures.hole.texture,
  '-1': textures.edge.texture,
  0: textures.ground.texture,
  1: textures.s.texture,
  2: textures.s.texture,
  3: textures.s.texture,
  4: textures.s.texture,
  5: textures.s.texture,
  7: textures.s.texture,
  6: textures.s.texture,
  8: textures.s.texture,
  9: textures.s.texture,
  10: textures.s.texture,
  11: textures.s.texture,
  12: textures.s.texture,
  13: textures.w_e.texture,
  14: textures.w_e.texture,
  15: textures.w_e.texture,
  16: textures.w_e.texture,
  17: textures.w_e.texture,
  18: textures.w_e.texture,
  19: textures.w_e.texture,
  20: textures.w_e.texture,
  21: textures.w_e.texture,
  22: textures.w_e.texture,
  23: textures.w_e.texture,
  24: textures.w_e.texture,
  25: textures.w_e.texture,
  26: textures.n_ne_e.texture,
  27: textures.n_ne_e.texture,
  28: textures.e.texture,
  29: textures.n_ne_e.texture,
  30: textures.n_ne_e.texture,
  31: textures.e.texture,
  32: textures.n_ne_e.texture,
  33: textures.e.texture,
  34: textures.n_nw_w.texture,
  35: textures.n_nw_w.texture,
  36: textures.w.texture,
  37: textures.n_nw_w.texture,
  38: textures.n_nw_w.texture,
  39: textures.n_nw_w.texture,
  40: textures.w.texture,
  41: textures.w.texture,
  42: textures.n.texture,
  43: textures.n.texture,
  44: textures.ne.texture,
  45: textures.nw.texture,
  46: textures.all.texture,
  47: textures.s.texture,
};

export const propsSprites = {
  // Traps
  [`${PropType.Peak}`]: textures.peak.texture,
  // Decor
  [`${PropType.Bone}`]: textures.bone.texture,
  [`${PropType.Flag}`]: textures.flag.texture,
  [`${PropType.CrateSilver}`]: textures.crate_silver.texture,
  [`${PropType.CrateWood}`]: textures.crate_wood.texture,
  [`${PropType.Handcuff1}`]: textures.handcuff_1.texture,
  [`${PropType.Handcuff2}`]: textures.handcuff_2.texture,
  [`${PropType.Lamp}`]: textures.lamp.texture,
  [`${PropType.Skull}`]: textures.skull.texture,
  [`${PropType.StonesLarge}`]: textures.stones_large.texture,
  [`${PropType.StonesSmall}`]: textures.stones_small.texture,
  [`${PropType.Torch}`]: textures.torch.texture,
  [`${PropType.WebLeft}`]: textures.web_left.texture,
  [`${PropType.WebRight}`]: textures.web_right.texture,
  // Items
  [`${PropType.HealthLarge}`]: textures.health_large.texture,
  [`${PropType.HealthSmall}`]: textures.health_small.texture,
  [`${PropType.KeyGold}`]: textures.key_gold.texture,
  [`${PropType.KeySilver}`]: textures.key_silver.texture,
  [`${PropType.ManaLarge}`]: textures.mana_large.texture,
  [`${PropType.ManaSmall}`]: textures.mana_small.texture,
  // Spawns
  [`${PropType.Ladder}`]: textures.ladder.texture,
};

export const monstersSprites = {
  [`${MonsterType.Bandit}`]: textures.bandit.texture,
  [`${MonsterType.CentaurFemale}`]: textures.centaur_female.texture,
  [`${MonsterType.CentaurMale}`]: textures.centaur_male.texture,
  [`${MonsterType.MushroomLarge}`]: textures.mushroom_large.texture,
  [`${MonsterType.MushroomSmall}`]: textures.mushroom_small.texture,
  [`${MonsterType.Skeleton}`]: textures.skeleton.texture,
  [`${MonsterType.Troll}`]: textures.troll.texture,
  [`${MonsterType.Wolf}`]: textures.wolf.texture,
};
